### ISSUE TITLE
play button greyed out

### ISSUE THREAD

**Issue by ChiliBeane** [MythicApp/Mythic#100]
**Describe the bug**
the play button for steam setup is greyed out

**To Reproduce**
1. Go to steam setup
2. Click play

**Expected behavior**
For steam to be playable.

**Screenshots**
![Screenshot 2024-06-18 at 5 53 00 PM](https://github.com/MythicApp/Mythic/assets/170266822/cbdccc20-84ef-48d9-a652-5d529a0e72d9)

**Mac (please complete the following information):**
Model: Mac air m2
Operating System: sonoma 14.5
App Version: 2.0.1

P.S i will just use 0.1.1 for steam until someone can fix this

**Comment by ChiliBeane** [comment]
neeeevermind it works now.

**Comment by asxrow66** [comment]
it usually means it's open already, maybe in the background.

**Comment by SirOreoII** [comment]
i got this before, maybe it's because you downloaded it on an external storage device? other than that im not sure.
