### ISSUE TITLE
[BUG] Game Thumbnail doesn't save

### ISSUE THREAD

**Issue by kyranm123** [MythicApp/Mythic#102]
**Describe the bug**
Game Thumbnail Doesnt save when switching to other tabs

**To Reproduce**
1. Go to settings and Change thumbnail URL
2. press esc and the thumbnail should be change
3. when switching to other tabs (for example switching to "settings" tab) or closing the app the thumbnail will dissappear

**Expected behavior**
the thumbnail should remain whether you change tabs or close the app

**Screenshots**
https://github.com/MythicApp/Mythic/assets/89881081/2c056610-a254-47b7-9e31-3c4ca184db29

**Mac (please complete the following information):**
Model: M1 Macbook pro 2020 8GB
Operating System: macOS Sonoma 14.5
App Version: 0.21-Alpha

**Comment by jeremybosma** [comment]
Seems similar to issue #99 do any other game settings save or work?

**Comment by kyranm123** [comment]
nope, imported game settings wont save

**Comment by kyranm123** [comment]
> Seems similar to issue #99 do any other game settings save or work?

Nope, any imported game settings wont save

**Comment by asxrow66** [comment]
Can't seem to replicate this issue.
