### ISSUE TITLE
[BUG] Can't move Mythic into the applications folder 

### ISSUE THREAD

**Issue by Bibue35** [MythicApp/Mythic#103]
**Describe the bug**
 Can't move Mythic into the applications folder 

**To Reproduce**
Steps to reproduce the behavior: just try to download it and move it into the application folder 
3. See error

**Expected behavior**
moving to the application folder 

**Screenshots**

**Mac (please complete the following information):**
Model: [m2. MacBook Air]
Operating System: [e.g. macOS Sequoia 15.0 BETA]
App Version: v0.2.1-alpha

**Additional context**

**Comment by jeremybosma** [comment]
Your `To Reproduce` does not really tell me much, do you happen to be on a school computer? You can also do this manually by just moving mythic from downloads in to applications

**Comment by asxrow66** [comment]
Please actually fill out the reproduction steps. Try uninstalling Mythic and re adding it to Applications.

**Comment by blackxfiied** [comment]
Can't reproduce.
