### ISSUE TITLE
cursor wont disappear in steam games.

### ISSUE THREAD

**Issue by ChiliBeane** [MythicApp/Mythic#106]
**Describe the bug**
title says it all. the cursor doesnt disappear when playing steam games.

**To Reproduce**
1. open steam game.
2. see cursor still there.

**Expected behavior**
my cursor not to be there

**Screenshots**
N/A

**Mac (please complete the following information):**
Model: MacBook Air m2 
Operating System: macOS Sonoma 14.5
App Version: 0.2.1

**Comment by asxrow66** [comment]
Seems to be an issue with the compatibility layer. What game exactly was it you were trying to play?

**Comment by ChiliBeane** [comment]
Dead island definitive edition. this has happened with several other games as well.
