### ISSUE TITLE
.Exes arent launching, steam included.

### ISSUE THREAD

**Issue by ChiliBeane** [MythicApp/Mythic#114]
**Describe the bug**
.exes do not launch.

**To Reproduce**
1. Go to library
2. Click the play button on any .exe

**Expected behavior**
for .exe to run.

**Screenshots**
N/A

**Mac (please complete the following information):**
Model: MacBook Air m2
Operating System: [e.g. macOS Sonoma 14.5
App Version: 0.2.1
 
I have tried resetting mythic. but it didnt work.

**Comment by asxrow66** [comment]
Try uninstall the engine. Head to Mythic settings and press Remove Mythic Engine. To reinstall the Mythic Engine, which you will have to do, you need to press Mythic in the menubar next to the Apple logo and press `Restart Onboarding`. Docs for this coming soon.

**Comment by ChiliBeane** [comment]
Ok, i did this, but nothing happened, im going to try reinstalling steam.

**Comment by ChiliBeane** [comment]
for some reason i cant even open the steam installer.

**Comment by asxrow66** [comment]
Did you reinstall the Mythic Engine?

**Comment by ChiliBeane** [comment]
im going to try other games, see if they work.

**Comment by ChiliBeane** [comment]
other games are working.

**Comment by ChiliBeane** [comment]
ok i tested something else and it seems only .exe's arent opening.

**Comment by asxrow66** [comment]
Did you import the Steam.exe or the entire folder?

**Comment by ChiliBeane** [comment]
steam.exe

**Comment by asxrow66** [comment]
reimport it with the folder steam.exe is located in

**Comment by ChiliBeane** [comment]
ok i will try that when i get a chance

**Comment by asxrow66** [comment]
follow these instructions if that doesn't work, note that steam will need to reinstalled.
Parts of this are located on the docs but I didn't finish them until now.
## Full Uninstall
To fully uninstall Mythic, including your bottles and your user info, we recommend [AppCleaner](appcleanerlinkhere).

Open AppCleaner and then simply drag the `Mythic.app` file into AppCleaner and let it locate all traces of Mythic on your device.

Once it has done so, press `Remove`. Then, delete the files from the trash. 
<img alt="nopermissionappcleaner" src="https://preview.redd.it/you-do-not-have-permission-to-move-the-files-to-the-trash-v0-m28mzsaw35sb1.png?width=1428&format=png&auto=webp&s=2eadbba95a3e87f8c370d2b0e411c97f18f21913" />
If an error appears saying it doesn't have permission to remove some files, look for the files still with a blue checkmark and then press the magnifying glass to the right of it and then delete the highlighted file/folder that opens in Finder.

**Comment by ChiliBeane** [comment]
i did this, and have reinstalled steamsetup.exe, but it will not launch

**Comment by ChiliBeane** [comment]
i think im going to try resetting mythic, and then using appcleaner.

**Comment by asxrow66** [comment]
Let me know how it goes.

**Comment by ChiliBeane** [comment]
it unfortunately still isnt working. steamsetup just opens the windows 64 preloader in my launchpad. but nothing else from there.

**Comment by SirOreoII** [comment]
While it downloads you should just leave it for a while. If that still doesn't work, redownload the steam launcher [here](https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe)

**Comment by ChiliBeane** [comment]
unfortunately, this doesn't work. The play button for steam setup on mythic just becomes an endlessly spinning wheel after clicking on it.

**Comment by asxrow66** [comment]
Mythic Engine issue.

> While it downloads you should just leave it for a while. If that still doesn't work, redownload the steam launcher [here](https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe)

It doesn't open, it has happened to me as well after Josh's useless Mythic Engine update.

**Comment by ChiliBeane** [comment]
good to know its not just me

**Comment by ChiliBeane** [comment]
this is fixed now in 0.3.2 so ima just close this. thx for the help everyone :)
