### ISSUE TITLE
[BUG] game isnt launching

### ISSUE THREAD

**Issue by ChiliBeane** [MythicApp/Mythic#132]
**Describe the bug**
when attempting to launch games from epic, nothing happens.

**To Reproduce**
1. Go to a game
2. Click play
3. See error

**Expected behavior**
games to start

**Screenshots**
N/A

**Mac (please complete the following information):**
Model: Mac air m2
Operating System: macos sequoia dev 3
App Version: 0.3.1

**Additional context**
after pressing play, theplay button either gets greyed out, or nothing happens.

**edit** 
this appears to only be occuring with one certain game tmnt sr.

**Comment by asxrow66** [comment]
What games?

**Comment by jeremybosma** [comment]
inactive + no context
