### ISSUE TITLE
[bug]: unable to change audio output from macbook speaker to airpod pro

### ISSUE THREAD

**Issue by tcchuin** [MythicApp/Mythic#139]
### Describe the bug

When i wear my airpod or have airpod connected earlier and changing my audio output to it, mythic's audio output stays on the speaker. All other apps works normally with the audio output change

### How to reproduce

1. Change audio output destination
2. Sounds should change

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by tcchuin** [comment]
a current workaround is to choose airpod as audio output BEFORE launching mythic. Maybe this is a non-issue by team? will let them close the issue if they decide this is the case

**Comment by blackxfiied** [comment]
new audio devices aren't registered if a game has already started afaik likely a `wine` thing, but for now that's not really where i'm focused right now
