### ISSUE TITLE
Add support DX9 Games

### ISSUE THREAD

**Issue by Segaboyman** [MythicApp/Mythic#14]
Hi!

I've been following your project since last year. It's pretty cool! 

But I have a question. Is there a chance that it will be possible to launch, if not all, then at least most DX9 games? Because, for example, I played Driver San Francisco through Wineskin. And this game was working until one day it stopped working. 

It would be really cool if you could play DX9 games through Mythic. Because I don't really want to install Parallels.

**Comment by blackxfiied** [comment]
You can! Mythic Engine comes with DXVK, which supports DX9.

**Comment by Segaboyman** [comment]
Wow! Games based on DX9 doesn't feel like slow-mo?) Because Wineskin have problems related running DX9 games.
