### ISSUE TITLE
[feat]: Xbox connection

### ISSUE THREAD

**Issue by H1B0B0** [MythicApp/Mythic#141]
### Feature description

Hey, your app is amazing! I suggest adding Xbox account integration to support installing Game Pass games on macOS. However, please prioritize the Steam feature first! 😍

### Before submitting

- [ ] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by jeremybosma** [comment]
I doubt running UWP games on a mac is possible, is there more you know about doing so? Any apps out there?

**Comment by H1B0B0** [comment]
I'm not entirely sure, but it seems that games are installed differently compared to Steam. With Xbox Game Pass, we'll have access to a vast library of games ready to play.

**Comment by asxrow66** [comment]
It can’t be done. Xbox is UWP and can’t be used in Mythic, even with the
setup EXE they have on their website.

**Comment by jeremybosma** [comment]
Check this uncovr ai search I did! https://uncovr.app/s/724373387f8f42a8b1d7958cedac388d

**Comment by jeremybosma** [comment]
Impossible
