### ISSUE TITLE
[bug]: Black Myth WuKong on Mac has error: please use the epic launcher to start the game

### ISSUE THREAD

**Issue by arelouse** [MythicApp/Mythic#143]
### Describe the bug

when attempting to launch Black Myth WuKong from epic, an error message said: Please use the Epic Launcher to start the game. Connection to the internet is required.

I also get the same message using Heroic to play WuKong. I don't know if it's the problem of this game itself.

### How to reproduce

1. Go to 'library'
2. Click to start 'Black Myth WuKong'
3. Wait a moment
4. See the error message "Please use the Epic Launcher to start the game. Connection to the internet is required."

### Mac & App Information

MacBook Pro Apple M1 Pro 32GB, MacOS: 14.5.0 (darwin)

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by blackxfiied** [comment]
seems to be a problem with the game -- unfortunately that means there's not a lot I can do.
