### ISSUE TITLE
[feat]: Compile Instructions

### ISSUE THREAD

**Issue by goober-183** [MythicApp/Mythic#150]
### Feature description

It would be cool to have build/compile instructions

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by JoshuaBrest** [comment]
They are not really needed, you can just build Mythic in Xcode.

**Comment by blackxfiied** [comment]
unnecessaryfor the reason @JoshuaBrest provided.
in the odd chance that the user compiles mythic using the command-line, chances are they'll be competent enough to compile it. (also you can just copy and paste from https://github.com/MythicApp/Mythic/blob/main/.github/workflows/build.yml)
