### ISSUE TITLE
[bug]: Cannot install to external SSD if there is not enough space on the built in drive

### ISSUE THREAD

**Issue by Dawauboy** [MythicApp/Mythic#156]
### Describe the bug

i have tried to install a game to an external ssd with more than enough space but got an error saying "Unable to proceed with Installation. Not enough available disk space! 36.78 GIB < 112.9 GIB" Which is also a bit strange because i have 49.19 GB free locally.

### How to reproduce

1. Go to Mythic app settings
2. Change default base path for games to an external SSD with enough space
3. Attempt to install a game that is larger than what is available on the built in drive but with enough space on the external SSD.
<img width="1440" alt="Screenshot Mythic" src="https://github.com/user-attachments/assets/81befce7-0014-4518-b447-39a6fe5300ce">

### Mac & App Information

- Model: Macbook Pro M1 2020 8gb OS: Sequoia 15.0.1

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by blackxfiied** [comment]
technically fixed for 0.4.1, there's no longer a pre-emptive installation checker
meaning once you change your disk Mythic will check the other disk **after** pressing install
fmi see 369cdcc17936cbe14bba3056c5ce506a24c10928
