### ISSUE TITLE
[bug]: Bad CPU type in executable

### ISSUE THREAD

**Issue by Ficusbaby** [MythicApp/Mythic#159]
### Describe the bug

When I am trying to sign into Epic Games and put the authorization code into Mythic, it says "The operation couldn't be completed. Bad CPU type in executable" I tried to redownload it but am coming back to the same issues... 

### How to reproduce

1. Try to install Mythic 
2. link your epic games account 

### Mac & App Information

MacBook Air 2019 
macOS Sonoma 

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by Ficusbaby** [comment]
I did see that there was a post #36 which is the exact problem I'm having but a different model of computer to mine. 
Was wondering if someone has troubleshooted this yet?

**Comment by asxrow66** [comment]
Intel CPU?

**Comment by blackxfiied** [comment]
Duplicate of #36
