### ISSUE TITLE
[bug]: Unable to install Fortnite

### ISSUE THREAD

**Issue by sharmasiddharth4** [MythicApp/Mythic#160]
### Describe the bug

When I click on the download button for Fortnite, then select the install location and the native platform and then when I click on install, it starts loading and it loads forever. The install doesn't start. Please fix this issue.

https://github.com/user-attachments/assets/b5dc42b3-5c66-420c-a591-7a03e0a723d9

### How to reproduce

1. Go to downloading Fortnite
2. Select the location and native platform.
3. Click on Install.
The installation doesn't start.

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by blackxfiied** [comment]
fixed 9db58ed79cea9edbd323b8aaca4c843ff2e7563b -- will be in next update
