### ISSUE TITLE
[bug]: Launch Arguments not being saved for local games

### ISSUE THREAD

**Issue by mvgiacomello** [MythicApp/Mythic#162]
### Describe the bug

I am trying to use Mythic to put all my legally acquired ROMS with their respective Emulators's as executable but the "Launch Arguments" doesn't seem to be saved when editing.

### How to reproduce

# Steps to reproduce (Version 0.4.0 - 2940):

1. Click the button to add a new game
1. Select "local" as source
1. Pick a name
1. Select "macOS" as platform
1. Browse the emulator app (in my case: `'/Applications/PCSX2.app'`)
1. Hit done and open the confugations for the new game
1. Enter the rom's path and emulator's params as "Launch Arguments". Mine looks like this: `-fastboot -fullscreen -disc "/Users/.../my-ps2.iso"`
1. Hit enter to save it (this action is really odd to have to do, took me a while to realize I had to press enter to confirm the action)
1. Run the game (it only opens the app, without args)
1. Go back to edit the game (you'll see the launch arguments is empty again)

_Note that on the terminal I can just run this command:_
```open /Applications/PCSX2.app --args -fastboot -fullscreen -disc "/Users/.../my-ps2"```

### Mac & App Information

M3 Macbook Air 24Gb/8Core, MacOS: Sequoia 15.0.1 (24A348), App: Version 0.4.0 - 2940

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by mvgiacomello** [comment]
From discord chat:
1. step 8 (UX) was fixed on commit `fef25f9`
1. launch stuff fixed on commit `d0e35c1`

**Comment by mvgiacomello** [comment]
I've pulled the latest Dev branch and built it locally. The arguments are still not being saved.

https://github.com/user-attachments/assets/f1b28256-903d-4e8e-9dd9-a01ae0ba8cc1

**Comment by blackxfiied** [comment]
try again now, i believe the problem is fixed
