### ISSUE TITLE
[bug]: The operation couldn't be completed. (NSURLErrorDomain error - 1011.)

### ISSUE THREAD

**Issue by Lalit64** [MythicApp/Mythic#172]
### Describe the bug

<img width="947" alt="SCR-20241114-ppdd" src="https://github.com/user-attachments/assets/513ba1c4-6a2c-46da-9b28-5a7eda34792a">

### How to reproduce

1. Download Mythic either from Homebrew or the Website
2. Open in, and sign in to your epic account
3. Click on next when it asks you to download mythic engine
4. Get this error

### Mac & App Information

- Model: MacBook Pro M1 Pro - OS: macOS Sequoia 15.1

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by blackxfiied** [comment]
Seems like the request timed out.
is this a recurring issue? because it's very unique and i haven't encountered this in the wild before.


`NSURLErrorTimedOut =            -1001,`
source: https://stackoverflow.com/questions/11028769/what-are-the-nsurlerrordomain-error-code-descriptions

**Comment by Lalit64** [comment]
@blackxfiied yes it happens everytime, I try to remove and reinstall the program but it doesn't work

**Comment by Lalit64** [comment]
@blackxfiied Tried just now and it's gone. I really don't know what caused it 🤷

**Comment by MichaelScherf** [comment]
I get the same issue today as well. Tried to reinstall everything, or skip the engine download to trigger it for an installed game, in the games overview. Always get the NSURLErrorDomain error -1011
