### ISSUE TITLE
[bug]: No games can be shown.

### ISSUE THREAD

**Issue by Lalit64** [MythicApp/Mythic#173]
### Describe the bug

![Uploading image.png…]()

### How to reproduce

1. Download Mythic and install it as per guide
2. Sign in to Epic Games and Install the Mythic Engine
3. Go to Library
4. Find no games there 🥟

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by blackxfiied** [comment]
image never uploaded, but have you tried relaunching?
issue is known

**Comment by Lalit64** [comment]
@blackxfiied Yeah I have tried relaunching

<img width="991" alt="image" src="https://github.com/user-attachments/assets/d20cf6f2-2d30-4536-bd5e-21324be0a254">

**Comment by Lalit64** [comment]
Hello, @vapidinfinity?

**Comment by jeremybosma** [comment]
Hello @Lalit64 no clue why the support is so poor nowadays but this is either because you havent linked your epic account in the accounts tab on the sidebar or have not yet imported a game
