### ISSUE TITLE
[BUG] Deleting games only makes them appear as uninstalled but does not actually remove the game files.

### ISSUE THREAD

**Issue by Jecta** [MythicApp/Mythic#19]
**Describe the bug**

**To Reproduce**
1. Go to library
2. Click on a game you want to uninstall
3. The library reloads and the game appears as uninstalled
4. Open finder and go to /Users/{yourusername}/Games
5. See that the game files are stil there

**Expected behavior**
The game files should be uninstalled

**Screenshots**
![image](https://github.com/MythicApp/Mythic/assets/68130184/6eda4d50-be0d-4d17-9310-0d0a897bfb2b)

**Mac (please complete the following information):**
Model: Macbook Air M2 16gb
Operating System: macOS Sonoma 14.2.1
App Version: 0.1.0 (2227)

**Comment by blackxfiied** [comment]
dirtyfixed [#9d9480f](https://github.com/MythicApp/Mythic/commit/9d9480f249f00c377fff712e42829510bc55fdba)
