### ISSUE TITLE
[BUG] Newly (un)installed games don't appear as installed before restarting the app

### ISSUE THREAD

**Issue by jeremybosma** [MythicApp/Mythic#20]
**Describe the bug**
Newly installed games don't appear as installed before restarting the app

**To Reproduce**
1. Go to library
2. Click on (un)install on any game you want to install
3. After it's fully (un)installed the library reloads
4. Scroll and see that the game is not (un)playable
5. Restart the app
6. Now it is (un)playable

**Expected behavior**
It should be (un)playable straight away after (un)install.

**Mac (please complete the following information):**
Model: Macbook Air M2 16gb
Operating System: macOS Sonoma 14.2.1
App Version: 0.1.0 (2227)

**Comment by the-P1neapple** [comment]
I have noticed that this also applies to adding a game to the library. I checked the defaults output for Mythic and the game does get added to the library (tested the localGamesLibrary dictionary with a fresh install). It may be a case of the library ui not refreshing its GameCards after importing, thus not being able to show any changes the available games until the launcher is restarted.

Hope this helps
