### ISSUE TITLE
[Feature] Controller Customisation

### ISSUE THREAD

**Issue by ZProLegend007** [MythicApp/Mythic#25]
A sub-menu in the settings to alter controller control mapping to specific keyboard keys or more and possibly cutsomization for proprietary things such as the LEDs on DS4+ controllers.

**Comment by jeremybosma** [comment]
I like this idea, however currently we're not focusing on external device customizations, through the compatibility layer games already have access to the inputs directly so we're currently sticking to relying on the games supported input and keybind mapping features.

Maybe one day we will reopen this.
