### ISSUE TITLE
[BUG] Games that need external launchers to open don't work

### ISSUE THREAD

**Issue by AsxrowIsHim** [MythicApp/Mythic#29]
**Description of Bug**
Games that need external launchers to open (such as Trackmania (needing Ubisoft Connect), Battlefield (needing EA app), GTAV (needing Rockstar Launcher), any other game that needs a external launcher.) will not open at all.

**To Reproduce**
1. Go to a game that needs an external launcher
2. Click on play
3. Nothing happens

**Expected behavior**
The external launcher opens and prompts me to launch the game and sign in.

**Screenshots**
Video of attempting to open Trackmania

https://github.com/MythicApp/Mythic/assets/71299637/2bd05151-17b8-4928-9acd-ea1246f19dd7

**Mac (please complete the following information):**
Model: MacBook Air M2 8GB RAM
Operating System: macOS Sonoma 14.4
App Version: First Release (0.1.0-alpha (2621))

**Comment by jeremybosma** [comment]
Not all custom launchers fail to launch, some are compatible with whisky’s wine/gptk some are not.

**Comment by AsxrowIsHim** [comment]
Steam is compatiable but some games in the Epic Store like the ones listed above, need their proprietary launcher to play the game.

**Comment by jeremybosma** [comment]
Unfortunately we're not in charge of the compatibility layer, neither are we in charge of external gaming launcher. Each launcher has a different app structure and some do not work. 

Like Epic Games which does not install we have created a native solution in our launcher and we plan to do this with as much launcher as possible taking care of the most mainstream ones first.
