### ISSUE TITLE
Mythic wont launch

### ISSUE THREAD

**Issue by ChiliBeane** [MythicApp/Mythic#30]
**Describe the bug**
When i launch mythic, even if i right click open it, it will not open.

**To Reproduce**
1. Go to finder
2. Click on applications
3. See Mythic
4. Open mythic

**Expected behavior**
For mythic to run

**Screenshots**
<img width="991" alt="Screenshot 2024-05-19 at 12 00 05 PM" src="https://github.com/MythicApp/Mythic/assets/170266822/020aa83d-3bf0-4a54-9819-07d2cd27c8aa">

**Mac (please complete the following information):**
Model: macbook air m2 
Operating System: macos sonoma 14.4
App Version: 0.1.0

**Additional context**

**Comment by AsxrowIsHim** [comment]
What type of Mac are you on **Silicon (M1,M2,M3)** or **Intel (i7,i5,i3)**?

**Comment by ChiliBeane** [comment]
silicon m2

**Comment by ChiliBeane** [comment]
im going to try doing a software update to see if that will fix it.

**Comment by jamesf-hub** [comment]
the first issue I see is that it's translated; mythic is a universal app and does not require translation from Rosetta

**Comment by AsxrowIsHim** [comment]
alright post back here how it goes or look for asxrow in the discord server

**Comment by AsxrowIsHim** [comment]
> the first issue I see is that it's translated; mythic is a universal app and does not require translation from Rosetta

true, since you're on an m2 machine, translation isn't needed since that is what mythic helps out with and if you were using an intel mac, i would advise using bootcamp but m2 so dont translate mythic.app

**Comment by ChiliBeane** [comment]
software update did nothing unfortunately

**Comment by ChiliBeane** [comment]
what should i do?

**Comment by AsxrowIsHim** [comment]
turn off translation on mythic

**Comment by ChiliBeane** [comment]
ok. how do i do that?

**Comment by AsxrowIsHim** [comment]
go to get info and look for "open in rosetta" and disable it

**Comment by AsxrowIsHim** [comment]
https://i.imgur.com/VYkzJTT.png

**Comment by ChiliBeane** [comment]
ok, will try, i think i might have tried that earlier and it didn't work, but i'll try again

**Comment by ChiliBeane** [comment]
yeah opening without rosetta doesnt work, it just displays the same error message

**Comment by AsxrowIsHim** [comment]
i cant figure out anything else, try reinstalling it. redownload it from the github and let me know or else keep the issue open and let jeremy or blackxfiled help out

**Comment by ChiliBeane** [comment]
alright, i will do that. thank you for your assistance.

**Comment by ChiliBeane** [comment]
ok, i did what you said, and now get this message upon launch:
<img width="252" alt="Screenshot 2024-05-19 at 1 42 44 PM" src="https://github.com/MythicApp/Mythic/assets/170266822/098a0c92-9b36-44ec-9f9d-a3b9505127b3">

**Comment by AsxrowIsHim** [comment]
open up privacy and security and press allow or open anyway

**Comment by ChiliBeane** [comment]
where in privacy and security to i click allow?

**Comment by AsxrowIsHim** [comment]
the bottom

**Comment by ChiliBeane** [comment]
under security?

**Comment by ChiliBeane** [comment]
my only security options for downloads are app store and identified developers
for some reason

**Comment by AsxrowIsHim** [comment]
thats how it should be, run mythic again and whent that popup shows up, press open anyway in the settings menu

**Comment by ChiliBeane** [comment]
whenever i do that i get this
<img width="991" alt="Screenshot 2024-05-19 at 12 00 05 PM" src="https://github.com/MythicApp/Mythic/assets/170266822/3ec86c75-b146-4454-82e7-d07999e4f0f1">

**Comment by ChiliBeane** [comment]
something i definitely should have mentioned earlier but forgot about is rhat tje forst time i ran mythic it actually worked. but after signing into epic, it closed and wouldnt re-open

**Comment by ChiliBeane** [comment]
what. the. actual. frick. I RESTARTED MY COMPUTER AGAIN. AND NOW MYTHIC WORKS!!!!!!!!!!!!!!!!!

**Comment by jeremybosma** [comment]
Could it be a ram issue?

**Comment by ChiliBeane** [comment]
i seriously dont know but its working now so im VERY happy.

**Comment by jeremybosma** [comment]
I’ll mark this as closed for now then.

**Comment by ChiliBeane** [comment]
thanks everyone for your help! greatly appreciated! :)
