### ISSUE TITLE
custom added games wont launch :/

### ISSUE THREAD

**Issue by maxiscoolithink** [MythicApp/Mythic#32]
im running the alpha version (first public release) and all my custom added games wont launch.
im on an M1 macbook air running sonoma 14.3.1.

**Comment by jeremybosma** [comment]
Could you tell me what game and if it occurs to everything. A test would be importing steaminstaller which should run no matter what. If that does run than the games you are importing are likely to not work with the compatibility layer.

**Comment by maxiscoolithink** [comment]
i fixed it. thanks for the help though
