### ISSUE TITLE
[BUG] The Bottle location in the Wine section of the menu is wrong (respectfully)

### ISSUE THREAD

**Issue by AsxrowIsHim** [MythicApp/Mythic#34]
**Describe the bug**
It says that the default bottle is located in ~/Library/Containers/Mythic/Bottles/Default but instead it is located in~/Library/Containers/xyz.blackxfiled/Bottles/Default
**To Reproduce**

**Expected behavior**
It should be in default folder that is listed.

**Screenshots**

**Mac (please complete the following information):**
Model: mba m2
Operating System: sonoma 14.4
App Version: alpha first release

**Comment by blackxfiied** [comment]
This is expected behaviour; Mythic prettifies URLs, and its bundle identifier (xyz.blackxfiied.Mythic) gets shortened to Mythic for conciseness' sake

**Comment by AsxrowIsHim** [comment]
Cool, thanks. I tried to install Steam and it worked but kept opening after I closed it and had to manually install it from Finder and couldn't find it. Thanks!
