### ISSUE TITLE
Cannot click Done when importing windows game

### ISSUE THREAD

**Issue by rj-lee** [MythicApp/Mythic#35]
**Describe the bug**

When trying to import a windows local windows game, the `Done` button is greyed out and I'm not sure what to change to complete the import

**To Reproduce**
1. Library > Import > Local
2. Enter name, choose Windows, point at an exe game file

**Expected behavior**
I should be able to click Done and play the game

**Screenshots**
![image](https://github.com/MythicApp/Mythic/assets/47578853/c5892e9c-b7ad-444b-b4c1-b64c70100222)

**Mac (please complete the following information):**
Model: MacBook Pro
Operating System: macOS Sonoma 14.4
App Version: 0.1.0-alpha

**Additional context**
I have successfully run this exe game with wine before

**Comment by blackxfiied** [comment]
I'm having trouble replicating this issue, I'll get back to you.

**Comment by maxiscoolithink** [comment]
ive been getting the same bug + another. instead of setting it to the exe file, set it to the folder its in, then reset it to the exe file. after that there is a bug where it doesnt open which i have made a report [https://github.com/MythicApp/Mythic/issues/32](url)

**Comment by AsxrowIsHim** [comment]
I get this bug occaisonally and happens at random times but it hasn't shown up for my last couple imports.
