### ISSUE TITLE
extended favourites section

### ISSUE THREAD

**Issue by k117-png** [MythicApp/Mythic#39]
<img width="1762" alt="image" src="https://github.com/MythicApp/Mythic/assets/113661499/61ee1586-793a-4542-9d9c-b4aa1165b8e6">

at the moment the favourites section takes up only a quarter of the screen, showing only two games at a time. using the bottom left corner for games would help view more games at a glance

**Comment by jeremybosma** [comment]
We're working on filtering https://github.com/orgs/MythicApp/projects/2/views/2?pane=issue&itemId=45003940 this way you can click favorites and only see those in the library view.

**Comment by jeremybosma** [comment]
We're working on filtering https://github.com/orgs/MythicApp/projects/2/views/2?pane=issue&itemId=45003940 this way you can click favorites and only see those in the library view.
