### ISSUE TITLE
[Suggestion]: Swift Implementation of Legendary

### ISSUE THREAD

**Issue by IsaacMarovitz** [MythicApp/Mythic#4]
The bulk of the codebase here is dedicated to parsing/handling the connection between Mythic and Legendary CLI. This connection would be unnecessary if Legendary was removed as a dependency and its functionality were implemented in Swift.

**Comment by blackxfiied** [comment]
This is true and has always been a vision from the start, however, legendary is a very extensive and stable implementation of epic games launcher functionality. To replicate this would require a lot of time, effort, and even more code to implement than just parsing legendary.

For this reason, this is a consideration but an extremely unlikely one to be implemented as of now.
