### ISSUE TITLE
When attempting to open Return to Moria Display Shows: Error The following components) are required to run this program: Microsoft Visual C+ + Runtime How to add this to mythic?

### ISSUE THREAD

**Issue by The-Warden-Jori** [MythicApp/Mythic#41]
But when trying to open Return to Moria display shows Error: The following components) are required to run this program:
Microsoft Visual C+ + Runtime

How do I do this?

**Same error message appears each time I attempt to open game**
3. See error

**Expected behavior**

**Screenshots**
![IMG_8897](https://github.com/MythicApp/Mythic/assets/156405591/49408ab4-cf27-4653-b961-3001580c99fd)

**Mac (please complete the following information):**
Model: [e.g. MacBook Air]
Operating System: [e.g. macOS Sonoma 14.1.1]
App Version:

**Additional context**

**Comment by AsxrowIsHim** [comment]
What I did is I downloaded this zip file  **[All in One C++ Visual Runtimes ](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/)** and then extracted it and imported the folder into Mythic, then run it from the library in Mythic and run the **"install_all.bat"** file and let it do its thing and it will close automatically, then run the game you originally wanted to play. You can now delete the C++ runtime from Mythic as it isn't needed anymore. That is the fix to your issue.

**Comment by The-Warden-Jori** [comment]
Thank you! I will try this as soon as I can!😅👍

**Comment by Smuzzy-waiii** [comment]
> What I did is I downloaded this zip file **[All in One C++ Visual Runtimes ](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/)** and then extracted it and imported the folder into Mythic, then run it from the library in Mythic and run the **"install_all.bat"** file and let it do its thing and it will close automatically, then run the game you originally wanted to play. You can now delete the C++ runtime from Mythic as it isn't needed anymore. That is the fix to your issue.

Cold you give a bit more info please. Specifically which folder to import into (Do you mean `~/Library/Containers/Mythic`) and how to run the bat file. I tried just running it from there terminal by using `chmod +x ./install_all.bat` and then `./install_all.bat` which didn't work and I dont think thats the correct way

**Comment by AsxrowIsHim** [comment]
Import the extracted folder into Mythic as you're importing it as a game. And when it opens up a folder when you press play on the folder in Mythic, double click on the install_all.bat, I can make a video when I get home later.

**Comment by jeremybosma** [comment]
> Import the extracted folder into Mythic as if you're importing it as a game. And when it opens up a folder when you press play on the folder in Mythic, double click on the install_all.bat, I can make a video when I get home later.

This is the solution, closing the issue. If this doesn't work for you somehow feel free to reopen.

**Comment by danieltaylor** [comment]
The Visual C++ Runtime installer that you need also comes prepackaged with the game files.  You do still have to install it as mentioned above, but you don't need to download any additional files:

![Screenshot 2024-12-17 at 9 48 13 PM](https://github.com/user-attachments/assets/92f6c7f1-2dca-4b62-9912-454e623f9235)
