### ISSUE TITLE
[BUG] Recently Played title does not get removed after unininstalling

### ISSUE THREAD

**Issue by the-P1neapple** [MythicApp/Mythic#42]
**Describe the bug**
When uninstalling a game from the launcher, the game card does not get removed from the recently played area

**To Reproduce**
1. Play an installed game
2. Uninstall the game from the library
3. Game still shows after uninstalled in Home. Even after restarting the app

**Expected behavior**
If game is uninstalled, remove it from the recently played

**Screenshots**

**Mac (please complete the following information):**
Model: Macbook Pro M2 2022
Operating System: Sonoma 14.4.1
App Version: 0.1.0-alpha (2621)

**Additional context**
None

**Comment by jeremybosma** [comment]
It is the most recently played game if it's installed or not does not matter, play another game and watch it disappear.

**Comment by jeremybosma** [comment]
Therefore i will close this issue
