### ISSUE TITLE
[Feature] Game Launch Arguments

### ISSUE THREAD

**Issue by the-P1neapple** [MythicApp/Mythic#43]
**Is your feature request related to a problem? Please describe.**
I want to launch Ghostrunner in DX12 but I am unable to unless I do command line arguments

**Describe the solution you'd like**
Create an optional field for launch arguments

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by jeremybosma** [comment]
This is planned already: https://github.com/orgs/MythicApp/projects/2/views/2?pane=issue&itemId=47108860
