### ISSUE TITLE
[BUG] Uninstalling an imported game does nothing

### ISSUE THREAD

**Issue by asxrow66** [MythicApp/Mythic#44]
**Describe the bug**
When you import anything into Mythic and try to uninstall it from the library, nothing happens. It doesn't matter if you restart it still is there.

**To Reproduce**
1. Import anything into Mythic
2. Attempt to uninstall it from the library
3. Find that nothing happens

**Expected behavior**
The imported game should be removed from your Mythic library.

**Mac (please complete the following information):**
Model: MacBook Air M2
Operating System: Sonoma 14.5
App Version: Alpha First Release

**Comment by blackxfiied** [comment]
Please elaborate.
Does the game not disappear from the library?
Does the importing view not disappear?

**Comment by jeremybosma** [comment]
Does not disappear

**Comment by AsxrowIsHim** [comment]
It doesn't disappear, it just deletes folder or file I imported and I used the uninstallation options that are inside of uninstall menu and it still wouldn't go away.

**Comment by AsxrowIsHim** [comment]
Can't upload the video of me trying to uninstall the video, but uploaded it to Google Drive.
`<iframe src="https://drive.google.com/file/d/1EorOPbi1oKlgfSKxXpQZRYUIGu_k2cRe/preview" width="640" height="480" allow="autoplay"></iframe>`

**Comment by AsxrowIsHim** [comment]
this issue is killing me

**Comment by jeremybosma** [comment]
This should be fixed in 0.2.1 or earlier. If the issue persists its likely because the game files don't exist anymore. if that is the case check uninstall from mythic only (keep the game files).

**Comment by asxrow66** [comment]
Restarting Mythic removes it from the library but it doesn't do unless it is restarted.

**Comment by blackxfiied** [comment]
fixed b2100f3032b85b8557c5a448685de6523e3d91e8
