### ISSUE TITLE
[Feature] Use Scroll Wheel to navigate the library

### ISSUE THREAD

**Issue by asxrow66** [MythicApp/Mythic#46]
**Is your feature request related to a problem? Please describe.**
Instead of using 2 fingers on the trackpad or dragging the scroll bar at the bottom, I would like to scroll normally on my mouse and trackpad

**Describe the solution you'd like**
Scroll the library instead of going sideways on the trackpad

**Comment by SliceOfTech** [comment]
That's how horizontal scrolling works on mac. That's scrolling normally.

**Comment by blackxfiied** [comment]
Cross-sectional scrolling may be more confusing to an end user than horizontal scrolling.
