### ISSUE TITLE
[BUG] Off center icons

### ISSUE THREAD

**Issue by asxrow66** [MythicApp/Mythic#47]
**Describe the bug**
The icons on game covers are off center

**Expected behavior**
Centered

**Screenshots**
![Screenshot 2024-05-19 at 11 00 48 PM](https://github.com/MythicApp/Mythic/assets/71299637/3f8fa2b9-0150-405d-a057-48398be8f645)

**Mac (please complete the following information):**
Model: MacBook Air M2
Operating System: Sonoma 14.5
App Version: first release

**Comment by blackxfiied** [comment]
SwiftUI bug; seems to be half-fixed in macOS Sequoia.
