### ISSUE TITLE
[BUG] Game (BF4) not downloading at all

### ISSUE THREAD

**Issue by seralith** [MythicApp/Mythic#50]
Battlefield 4 refuses to download. I've even installed EA app but that hasn't seemed to help the issue. I press download, it asks me to confirm and choose where the download location will be, but then I press install, and it proceeds to close the install request, show the downloading indicator for maybe half a second, then completely stops. 

1. Go to Battlefield 4
2. Click on download
3. See error

**Expected behavior**
I expected the game to download

**Mac (please complete the following information):**
Model: MacBook Pro M1, 16gb ram, around 150 gigs of storage remaining
Operating System: [e.g. macOS Sonoma 14.1.1]
App Version: Latest

**Comment by blackxfiied** [comment]
This is a known issue, Mythic doesn't display its errors on alerts at the moment, only notifications.

**Comment by blackxfiied** [comment]
External launchers such as origin are required to install certain games, I don't plan on supporting this just yet though

**Comment by blackxfiied** [comment]
Mythic will now tell you what's going on, closing this issue for staleness though
