### ISSUE TITLE
[Feature] Homebrew Cask

### ISSUE THREAD

**Issue by Lalit64** [MythicApp/Mythic#51]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be good to have a Homebrew Cask

**Describe alternatives you've considered**
None

**Additional context**
Self Explanatory

**Comment by mattmaniak** [comment]
Already tried to do it on my own. Application Bundle requires notarization to be Cask-eligible which is not present for `0.3.1`. Cask [PR](https://github.com/Homebrew/homebrew-cask/pull/178921) got closed.

**Comment by asxrow66** [comment]
> Application Bundle requires notarization to be Cask-eligible which is not present for `0.3.1`.

It is on the way! It just needs to be implemented. Thanks for contributing though!

**Comment by Vfposselt** [comment]
Hey! Any news on the implementation?

**Comment by asxrow66** [comment]
Not yet. I'll DM @blackxfiied about implementing it. It's already paid for and everything, just needs to be actually implemented into Mythic itself.

**Comment by asxrow66** [comment]
Closing though. Will re-open if needed.

**Comment by asxrow66** [comment]
haha nevermind because github automatically put it as done

**Comment by blackxfiied** [comment]
> Already tried to do it on my own. Application Bundle requires notarization to be Cask-eligible which is not present for `0.3.1`. Cask [PR](https://github.com/Homebrew/homebrew-cask/pull/178921) got closed.

try now, mythic's notarized as of the latest version (0.4.1)

**Comment by mattmaniak** [comment]
Will try. Thanks.

**Comment by mattmaniak** [comment]
Could you add "Mythic.zip" to the 0.4.1 Tag? I have defined to download Mythic build from tags in Homebrew Cask (`https://github.com/MythicApp/Mythic/releases/download/v#{version}/Mythic.zip`). Optionally please provide me a direct link to the latest build as https://getmythic.app/download/ is implicit.

**Comment by JoshuaBrest** [comment]
> Could you add "Mythic.zip" to the 0.4.1 Tag? I have defined to download Mythic build from tags in Homebrew Cask (`https://github.com/MythicApp/Mythic/releases/download/v#{version}/Mythic.zip`). Optionally please provide me a direct link to the latest build as [getmythic.app/download](https://getmythic.app/download/) is implicit.

For now, the Download URL is [https://dl.getmythic.app/sparkle-temp/Mythic-VERSION.zip](https://dl.getmythic.app/sparkle-temp/Mythic-VERSION.zip) It might be changed in the future, however. For livecheck, use the appcast at [https://dl.getmythic.app/sparkle-temp/appcast.xml](https://dl.getmythic.app/sparkle-temp/appcast.xml).

**Comment by mattmaniak** [comment]
Already [merged](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/m/mythic.rb). Waiting for an availability to download. Thanks for notarization @JoshuaBrest again.

**Comment by mattmaniak** [comment]
Mythic is now [downloadable](https://formulae.brew.sh/cask/mythic) via Brew!
