### ISSUE TITLE
[BUG] Installing Mythic Engine cancel button does not work

### ISSUE THREAD

**Issue by danieltaylor** [MythicApp/Mythic#54]
**Describe the bug**
The cancel button while installing Mythic Engine does not do anything.

**To Reproduce**
1. After logging into Epic on initial setup, click continue when asked to install Mythic Engine.
2. Click on the X
3. Nothing happens

**Expected behavior**
Download/install should cancel and user should be returned to the previous page.

**Screenshots**
![Screenshot 2024-05-20 at 5 35 41 PM](https://github.com/MythicApp/Mythic/assets/6980323/f0cc48c1-c7a1-45f1-be84-1d28191bcb7e)

**Mac:**
Model: MacBook Pro M3
Operating System: macOS Sonoma 14.4.1
App Version: v0.1.1-alpha

**Comment by blackxfiied** [comment]
The cancel button is disabled (it's greyed out) at this time while I find a way to delete the temporary file created by the installer.
