### ISSUE TITLE
[Feature] Open .exe files from Finder

### ISSUE THREAD

**Issue by AsxrowIsHim** [MythicApp/Mythic#55]
**Describe the solution you'd like**
When I download a .exe file from the internet, I would like to open it from Finder and it will open up in the Default bottle.

**Describe alternatives you've considered**
Import

**Comment by blackxfiied** [comment]
As to not undercut the likes of Whisky, I've chosen not to implement this feature, but rather to implement quick-opening Windows executables from bottle settings.
