### ISSUE TITLE
[Feature] Change library grid size

### ISSUE THREAD

**Issue by Pieter-Jan-iO** [MythicApp/Mythic#57]
**Is your feature request related to a problem? Please describe.**
The library grid is rather big now (only 2 rows), if you have a lot of games it's not really clear.

**Describe the solution you'd like**
Make it possible to change the grid size or add a button to switch to a list view.
Also I think a vertical scroll would be better instead of horizontal.
The library of Epic Games is a good example.

I really like the style of the tiles. App looks very good!

**Comment by asxrow66** [comment]
#37
