### ISSUE TITLE
Crush

### ISSUE THREAD

**Issue by aminouser** [MythicApp/Mythic#60]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Mythic [1038]
Path:                  /Applications/Mythic.app/Contents/MacOS/Mythic
Identifier:            xyz.blackxfiied.Mythic
Version:               0.1.1-alpha (2630)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-05-21 21:14:28.0029 +0800
OS Version:            macOS 14.0 (23A5286g)
Report Version:        12
Anonymous UUID:        2D8E6209-DA64-C2F3-60AF-B5C606044DD0

Time Awake Since Boot: 69 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: _$s7SwiftUI26WindowBackgroundShapeStyleVACycfC
Referenced from: <D767ACBC-B5C8-3B8D-858D-E2E2F79A1FB7> /Applications/Mythic.app/Contents/MacOS/Mythic
Expected in:     <5CBA1C3F-43C5-3529-8130-C71BAB1413D5> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x190d89bc8 __abort_with_payload + 8
1   dyld                          	       0x190d96188 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x190d961bc abort_with_payload + 16
3   dyld                          	       0x190d1d518 dyld4::halt(char const*, dyld4::StructuredError const*) + 304
4   dyld                          	       0x190d1a1e8 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3884
5   dyld                          	       0x190d18f44 start + 1948

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016f024d30   x3: 0x00000000000000b2
    x4: 0x000000016f024930   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x00000000000007e0
    x8: 0x0000000000000020   x9: 0x000000016f02489c  x10: 0x000000000000000a  x11: 0x0000000000000000
   x12: 0x0000000000000031  x13: 0x0000000000000000  x14: 0x00000002520f3f7c  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x0000000190d1637c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f024930  x21: 0x00000000000000b2  x22: 0x000000016f024d30  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0x00000001013dad80  x26: 0x0000000000000e10  x27: 0x00000001013dad80
   x28: 0x000000001f070004   fp: 0x000000016f024900   lr: 0x0000000190d96188
    sp: 0x000000016f0248c0   pc: 0x0000000190d89bc8 cpsr: 0x80001000
   far: 0x000000010141c000  esr: 0x56000080  Address size fault

Binary Images:
       0x1014f0000 -        0x101533fff org.sparkle-project.Sparkle (2.6.2) <387c652c-43e0-3ed4-8d24-25f881186cbf> /Applications/Mythic.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x100dd8000 -        0x100f63fff xyz.blackxfiied.Mythic (0.1.1-alpha) <d767acbc-b5c8-3b8d-858d-e2e2f79a1fb7> /Applications/Mythic.app/Contents/MacOS/Mythic
       0x190d13000 -        0x190da68fb dyld (*) <b1f98040-1e0e-39dc-9498-bd7f616f30b4> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                            1378K      246 
__AUTH_CONST                      22.8M      430 
__CTF                               824        1 
__DATA                            9780K      416 
__DATA_CONST                      20.6M      436 
__DATA_DIRTY                      1277K      135 
__FONT_DATA                        2352        1 
__LINKEDIT                       878.9M        3 
__OBJC_RO                         70.3M        1 
__OBJC_RW                         2144K        1 
__TEXT                           515.6M      451 
dyld private memory               4384K        4 
shared memory                       32K        1 
===========                     =======  ======= 
TOTAL                              1.6G     2129 

-----------
Full Report
-----------

{"app_name":"Mythic","timestamp":"2024-05-21 21:14:28.00 +0800","app_version":"0.1.1-alpha","slice_uuid":"d767acbc-b5c8-3b8d-858d-e2e2f79a1fb7","build_version":"2630","platform":1,"bundleID":"xyz.blackxfiied.Mythic","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A5286g)","roots_installed":0,"name":"Mythic","incident_id":"93234644-5642-4257-8483-46CD18DCAA0C"}
{
  "uptime" : 69,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,7",
  "coalitionID" : 1136,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A5286g",
    "releaseType" : "User"
  },
  "captureTime" : "2024-05-21 21:14:28.0029 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "93234644-5642-4257-8483-46CD18DCAA0C",
  "pid" : 1038,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-05-21 21:14:27.9889 +0800",
  "procStartAbsTime" : 1667043925,
  "procExitAbsTime" : 1667332599,
  "procName" : "Mythic",
  "procPath" : "\/Applications\/Mythic.app\/Contents\/MacOS\/Mythic",
  "bundleInfo" : {"CFBundleShortVersionString":"0.1.1-alpha","CFBundleVersion":"2630","CFBundleIdentifier":"xyz.blackxfiied.Mythic"},
  "storeInfo" : {"deviceIdentifierForVendor":"89CC6C1A-EC41-5A2C-89A6-FA8A48306E61","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "xyz.blackxfiied.Mythic",
  "crashReporterKey" : "2D8E6209-DA64-C2F3-60AF-B5C606044DD0",
  "lowPowerMode" : 1,
  "codeSigningID" : "xyz.blackxfiied.Mythic",
  "codeSigningTeamID" : "67ZBY275P8",
  "codeSigningFlags" : 1644245777,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"NAEAANQAAAAQAQAAGAEAACABAAAoAQAAMAEAAEwBAAAwQYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkaww\/pe\/AwCR\/XvBqP8PX9bAA1\/WEC2A0g=="},
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: _$s7SwiftUI26WindowBackgroundShapeStyleVACycfC","Referenced from: <D767ACBC-B5C8-3B8D-858D-E2E2F79A1FB7> \/Applications\/Mythic.app\/Contents\/MacOS\/Mythic","Expected in:     <5CBA1C3F-43C5-3529-8130-C71BAB1413D5> \/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":9255,"threadState":{"x":[{"value":6},{"value":4},{"value":6157389104},{"value":178},{"value":6157388080},{"value":0},{"value":0},{"value":2016},{"value":32},{"value":6157387932},{"value":10},{"value":0},{"value":49},{"value":0},{"value":9966665596},{"value":32768},{"value":521},{"value":6724608892,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6157388080},{"value":178},{"value":6157389104},{"value":4},{"value":6},{"value":4315786624},{"value":3600},{"value":4315786624},{"value":520552452}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6725132680},"cpsr":{"value":2147487744},"fp":{"value":6157388032},"sp":{"value":6157387968},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6725082056,"matchesCrashFrame":1},"far":{"value":4316053504}},"frames":[{"imageOffset":486344,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":2},{"imageOffset":536968,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":2},{"imageOffset":537020,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":2},{"imageOffset":42264,"symbol":"dyld4::halt(char const*, dyld4::StructuredError const*)","symbolLocation":304,"imageIndex":2},{"imageOffset":29160,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3884,"imageIndex":2},{"imageOffset":24388,"symbol":"start","symbolLocation":1948,"imageIndex":2}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4316921856,
    "CFBundleShortVersionString" : "2.6.2",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "387c652c-43e0-3ed4-8d24-25f881186cbf",
    "path" : "\/Applications\/Mythic.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2038"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4309483520,
    "CFBundleShortVersionString" : "0.1.1-alpha",
    "CFBundleIdentifier" : "xyz.blackxfiied.Mythic",
    "size" : 1622016,
    "uuid" : "d767acbc-b5c8-3b8d-858d-e2e2f79a1fb7",
    "path" : "\/Applications\/Mythic.app\/Contents\/MacOS\/Mythic",
    "name" : "Mythic",
    "CFBundleVersion" : "2630"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6724595712,
    "size" : 604412,
    "uuid" : "b1f98040-1e0e-39dc-9498-bd7f616f30b4",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6723846144,
  "size" : 3958521856,
  "uuid" : "0dc17e1a-5bf7-38f4-986f-d42324b1f4c7"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1378K      246 \n__AUTH_CONST                      22.8M      430 \n__CTF                               824        1 \n__DATA                            9780K      416 \n__DATA_CONST                      20.6M      436 \n__DATA_DIRTY                      1277K      135 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       878.9M        3 \n__OBJC_RO                         70.3M        1 \n__OBJC_RW                         2144K        1 \n__TEXT                           515.6M      451 \ndyld private memory               4384K        4 \nshared memory                       32K        1 \n===========                     =======  ======= \nTOTAL                              1.6G     2129 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "0ea5660e46452402882d0e39ce14d48578a562a4",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "654439cdafbf5b61207873a9",
      "factorPackIds" : {

      },
      "deploymentId" : 250000003
    },
    {
      "rolloutId" : "63fe4dd2238e7b23a1f3067d",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_CAM_AB_TESTING" : "643938cae7268460c2e35a16"
      },
      "deploymentId" : 250000004
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,7, BootROM 10151.0.172.0.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jun 21 2023 23:17:15 version 18.20.436.0.7.8.161 FWID 01-782b6522
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by AsxrowIsHim** [comment]
Have you attempted to reinstall Mythic? If not, I would install App Cleaner (it's free) and uninstall Mythic from there and then download version 0.1.1.

**Comment by blackxfiied** [comment]
What were you doing when the app crashed?
Without more context, it's hard to help out.

**Comment by blackxfiied** [comment]
stale

**Comment by asxrow66** [comment]
> What were you doing when the app crashed?
I believe this was someone from the Discord and I told them to do this except they should have said what they were doing.

**Comment by blackxfiied** [comment]
either way it's unhelpful so i'll have to close this one
