### ISSUE TITLE
[Feature] Make Windows Default Custom Import

### ISSUE THREAD

**Issue by jeremybosma** [MythicApp/Mythic#64]
Right now when you import a custom game it defaults macOS but let's be real, everyone is here to run Windows games on macOS so it would save a few clicks and confusion in most scenarios

**Comment by asxrow66** [comment]
yeah and also if you add the name of what you want to import, then change it to windows, the name resets and has to be typed again

**Comment by blackxfiied** [comment]
Both decisions are intentional.
Mythic is a macOS-first launcher, meaning that if there is a native version of a game available, that should be the version Mythic will download by default.

This is to prevent issues and ensure the smoothest performance possible.

**Comment by asxrow66** [comment]
1. A lot of games run better on Windows even when translated from Mac which means the Mac version may not be the best.
2. This issue's fix should only be when importing software or games.

**Comment by blackxfiied** [comment]
Decision is final.
From an end-user's perspective, there's a higher chance they'll need to import a macOS game, as they can be externally downloaded easier than Windows games.
