### ISSUE TITLE
[BUG] Unable to use basic OS features while game is in full screen

### ISSUE THREAD

**Issue by shadeydo** [MythicApp/Mythic#69]
**Describe the bug**
Menu bar, dock, and all other system features like notifications and desktop switching, are inaccessible while certain games are launched in full screen, preventing user from leaving window unless game is quit. (cmd q also doesnt work)

**To Reproduce**
1. Download and launch Rocket league through Epic games launcher in mythic
2. Make sure game is in full screen
3. See bug

**Expected behavior**
- Notification pop ups show
- upper menu bar is accessible (if hover to show is enabled in OS settings)
- Dock is accessible (if hover to show is enabled in OS settings)
- able to switch to adjacent desktop workspaces while the game is running in the background
- able to press cmd space to use spotlight search
- able to quit game at any time with cmd q shortcut

**Mac (please complete the following information):**
Model: M1 Macbook Air, 2020, 16gb ram 
Operating System: macOS Sonoma 14.5
App Version: 0.1.1-alpha (2630)

**Additional context**
Not sure if this is bug universal for all games, but others on the discord have expressed a similar issue for games other than rocket league.

**Comment by asxrow66** [comment]
this bug is not universal in all games and only affects some games. rocket league runs weird on native windows because of how it is shown and ran so i think it's because of the game. blackxfiied could maybe do something but overall it is the games fault

**Comment by blackxfiied** [comment]
This is normal rocket league behaviour, and is unfortunately out of my control.
