### ISSUE TITLE
[BUG] Unreadable text on certain cover arts

### ISSUE THREAD

**Issue by ilgrandeanonimo** [MythicApp/Mythic#73]
**Is your feature request related to a problem? Please describe.**
In light mode the game names are black and not well readable

**Describe the solution you'd like**
The text should be, white if the background is dark or black if the background is light. regardless of the system theme

**Describe alternatives you've considered**
No Answer

**Additional context**
<img width="383" alt="Screenshot 2024-05-26 alle 10 34 28" src="https://github.com/MythicApp/Mythic/assets/65458792/2fb7389f-ef68-45e6-a7a7-63807533dbbf">

**Comment by blackxfiied** [comment]
fixed 77d38de -- will upstream with next Mythic release
