### ISSUE TITLE
[BUG] App lags during games download

### ISSUE THREAD

**Issue by ilgrandeanonimo** [MythicApp/Mythic#74]
**Describe the bug**
While downloading the game(s) the app start lagging, the system continues to remain fluid

**To Reproduce**
Just download a game

**Expected behavior**
The app doesn't lag

**Screenshots**
None

**Mac (please complete the following information):**
Model: MacBook Air M1 8Core GPU & CPU
Operating System: macOS Sonoma 14.5
App Version: 0.1.1-alpha

**Additional context**
None

**Comment by blackxfiied** [comment]
Known issue, awaiting fix in `dev` branch

**Comment by marcusziade** [comment]
That URL goes to the repo root 🤔 

What's the latest on this, @blackxfiied ?

**Comment by blackxfiied** [comment]
Behind time, I think the problem has to do with completion handlers, strangely enough.
I've been planning to leave those behind and focus on using the Combine framework instead.
Just haven't had time lately.

**Comment by marcusziade** [comment]
I think we can solve this using Swift concurrency. I believe a lot of the code is currently running on the main thread. I think I'm able to fix this. But I'll need some time to do this.

**Comment by blackxfiied** [comment]
Fixed in 65684f4f4d2d6c75341facaf5be2f47ba4d2e0c4.
