### ISSUE TITLE
[BUG] Cannot change Wine bottle for imported local game

### ISSUE THREAD

**Issue by sislakd** [MythicApp/Mythic#76]
**Describe the bug**
Cannot change Wine bottle for imported local game. Change "Current bottle" and "Close" always keep "Default" as Current bottle for the game.

**To Reproduce**
1. Go to Management/Wine and create new bottle using "+" symbol. You can use whatever name you want and use Done button to create new bottle.
2. Go to Library and use "+" symbol to perform Import. Choose "Local", select native platform as "Windows", provide name of the game and browse for your game location. At the end use "Done" to finalize the import of the game.
3. Reload Library to have your imported game to be shown. Use the second icon to edit details for the game. Now, try to change Wine/Current bottle to the bottle created in the step 1. So far all looks good. Close the details window.
4. Use the second icon on the game to edit details for the game once again. The change bottle is not remembered and the Default is used again.
5. It doesn't seem to be just UI issue. If you start the imported game, it is always started within Default bottle. Thus, the bottle cannot be changed at all.

**Expected behavior**
Wine bottle can be changed for the imported local game:
* the changed bottle is remembered for the game - the next time Mythic is started the configured bottle stays there
* the changed bottle is used for running the game
Currently all imported local games are always using Default bottle.

**Mac (please complete the following information):**
Model: MacBook Pro [e.g. MacBook Air]
Operating System: Sonoma 14.5
App Version: 0.1.1-alpha (2630) but I've also verified that the same issue is in the latest code in the main and dev branches

**Comment by blackxfiied** [comment]
Can't reproduce this issue, unfortunately 👍🏾
