### ISSUE TITLE
[Feature] Add support for syncing saved games with Epic Cloud

### ISSUE THREAD

**Issue by scelis** [MythicApp/Mythic#77]
It would be nice to be able to sync saved games with Epic Cloud. Legendary supports this with `legendary sync-saves`. Maybe once every 5 minutes and a with a force sync button.

**Comment by blackxfiied** [comment]
All done! (60e9475d44962a5016bcafcb7df596407775d8da, 3ee89883aa563013608be5139b19b17d6ff061e4)
