### ISSUE TITLE
[BUG] Installing Fornite always 0%

### ISSUE THREAD

**Issue by CodyBontecou** [MythicApp/Mythic#78]
**Describe the bug**
No matter how long I wait, it's always at 0%.

**To Reproduce**
1. Fresh install of Mythic
2. Click on install Fortnite
3. See error

**Expected behavior**
I expect the download to occur.

**Screenshots**
![CleanShot 2024-05-29 at 09 37 20@2x](https://github.com/MythicApp/Mythic/assets/20440899/c6037c36-764d-43ae-ac91-4c406b1bc746)

**Mac (please complete the following information):**
Model: M1 Max, 64gb Ram
Operating System: 14.5 (23F79)
App Version: Version 0.1.1-alpha (2630)

**Additional context**

**Comment by asxrow66** [comment]
For one, Fortnite **CANNOT** be played on Mythic or an app like it or any virtual machine because of its *Kernel Level Anti-Cheat* and is a **waste** of storage and **time.** This does seem to happen to a lot of people trying to download Fortnite.

**Comment by CodyBontecou** [comment]
Ah, I guess I assumed it would work given it was the default game that Mythic showcases.

**Comment by asxrow66** [comment]
>  default game that Mythic showcases.
Might just be that pretty much everyone owns it. You can find compatible games [here](https://docs.google.com/spreadsheets/d/1W_1UexC1VOcbP2CHhoZBR5-8koH-ZPxJBDWntwH-tsc/edit#gid=0) and feel free to add any at the Google Form link at the top. Thanks!

**Comment by blackxfiied** [comment]
Can't reproduce, unfortunately.
