### ISSUE TITLE
[BUG] GTAV Launcher not initialised

### ISSUE THREAD

**Issue by burakssen** [MythicApp/Mythic#80]
**Describe the bug**
After installing GTAV it gives Rockstar Launcher is not initialised error.

**To Reproduce**
1. Go to GTAV game
2. Click on run button
3. See error

**Expected behavior**
It should successfully open the Rockstar Launcher.

**Screenshots**
<img width="271" alt="image" src="https://github.com/MythicApp/Mythic/assets/43742977/76883a46-2c13-49a7-ac99-09989465809d">

**Mac (please complete the following information):**
Model: MacBook Pro 14 inch
Operating System: macOS Sonoma 14.5 arm64
App Version: Mythic 0.1.1-alpha (2630)

**Comment by asxrow66** [comment]
Hopefully can be fixed when Winetricks is fixed but for now, any fix I have attempted, will not fix it.

**Comment by asxrow66** [comment]
compatibiliy layer issue and gptk 2 update doesn't fix, awaiting winetricks fix

**Comment by jeremybosma** [comment]
This is a compatibility layer issue and is not correlated to the Mythic app
