### ISSUE TITLE
[BUG] Download Speed Text Wrapping

### ISSUE THREAD

**Issue by PeterBrownie** [MythicApp/Mythic#89]
**Describe the bug**
This is a simple visual bug in the window that displays install/download information. See screenshot. 

Sometimes the 'X MB Downloaded' text label will wrap to 2 lines. This causes the install information container to grow a few pixels taller than the window can fit, causing a scroll bar to appear.

**To Reproduce**
1. Be downloading something
2. Go to 'Downloads' menu.
3. Click on the 'i' button to view more information
4. Wait until the download speed is larger than 9 MB/s
5. See bug. 

**Expected behavior**
Because all the information is still visible, the scroll bar should not appear. 
The solution would be to increase the space the text label is given, so it doesn't wrap.

**Screenshots**
<img width="488" alt="image" src="https://github.com/MythicApp/Mythic/assets/31493909/a7da6aff-7d9f-4301-932d-bc4b8cf130fe">

**Mac:**
Model: Macbook Pro M3 Pro 1TB
Operating System: macOS 15.0 Beta (24A5264n)
App Version: 0.2.0

**Additional context**
Inconsistently, when the download speed is exactly 11 MB/s, the spacing is okay.
Also, in the downloads menu, the 'i' in the 'i' button is not centered...

**Comment by PeterBrownie** [comment]
Hold up. I'm wrong I think!

The issue might actually be caused by the Download speed itself going into 2 digits.

**Comment by blackxfiied** [comment]
Icons being off-center is a SwiftUI bug i'm aware of.
A temporary solution would be to manually resize the sheet in which the download information is displayed.

I'll begin working on a fix.
