### ISSUE TITLE
incompatible games should be grayed out

### ISSUE THREAD

**Issue by Anatharias** [MythicApp/Mythic#9]
I think adding a grayed out tile on top of games known to not work would be great.
Destiny 2 - requires Easy AntiCheat 2 - is not going to work under macOS whatever the mean..
So graying out the tile in the list of titles, with a tooltip explaining why it is not possible to install/run it.
Same for games that requires AVX instructions (https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit#AVX)
Also, maybe adding a clickable link to the macgaming wiki compatibility page.

Even, let's get wild... for any game that has a wiki page, offer a link to said page in order to follow the recommendations.
For instance, Horizon : Wero Dawn has a weird requirement for it to run full speed. this is not explained on the wiki page, instead a dude crated a video for it.
Maybe then offer a clickable google link with search words, like "game name" + mac + fix + tweak, that'll look like this, once on google:
Horizon Zero Dawn mac tweak fix

**Comment by Jecta** [comment]
That's a cool idea! How about allowing the user to install and run the game regardless? For instance, we could implement a pop-up that mentions the title might not run, with options for 'Abort' and 'Run Anyway'.

**Comment by ZProLegend007** [comment]
> That's a cool idea! How about allowing the user to install and run the game regardless? For instance, we could implement a pop-up that mentions the title might not run, with options for 'Abort' and 'Run Anyway'.

Could add a little circular orange warning sign on those games with a message that appears when the mouse hovers over it saying something like “This title is not fully  compatible, it might not run as expected or at all.”

**Comment by blackxfiied** [comment]
Difficult to do at this time, marking as stale.
