### ISSUE TITLE
[BUG] Steam installer not opening - macOS Sequoia

### ISSUE THREAD

**Issue by KnedlikMCPE** [MythicApp/Mythic#90]
**Describe the bug**
So, for some reason, with Mythic 0.2 and macOS Sequoia, the Steam installer fails to load. I have a suspicion it's an engine issue, but I don't know how to confirm that.

**To Reproduce**
1. Install Mythic 0.2 on Sequoia
2. Install MythicEngine during onboarding
3. Try to launch SteamSetup.exe

**Expected behavior**
SteamSetup should at the very least show some signs of attempting to launch

**Screenshots**
N/A

**Mac (please complete the following information):**
Model: MacBook Pro 13' M1 8GB
Operating System: macOS Sequoia 15.0
App Version: 0.2

**Additional context**
N/A

**Comment by jeremybosma** [comment]
This issue was because our Mythic engine was broken, open Mythic and click update when it tells you to, after that you should be able to run your games/software again. For if anything happens again join our discord https://discord.gg/qbc32gtZDt if you want a live blog on our fix.
