### ISSUE TITLE
[BUG] GTA 5 do not want to start download

### ISSUE THREAD

**Issue by sauciss0nsec** [MythicApp/Mythic#91]
**Describe the bug**
Hi, I wanted to download GTA 5 from my epic library. When I start the download, I'd during 2 seconds and after that, Mythic tell me the download it's done but its false, the game is not downloaded.

**To Reproduce**
1. Go to library
2. Click on 'download, just below the title of the game
3. confirm the download in the window ask the download path
4. the download start
5. one second later, mythic tell it's done
6. See error

**Expected behavior**
I happened the download can be finishing and after that just play.

**Screenshots**
in attached file

https://github.com/MythicApp/Mythic/assets/172921111/52ff5707-9f25-4076-95a0-de8544159074

**Mac (please complete the following information):**
Model: M1 MacBook Pro 13", 16go of RAM, 1to of storage
Operating System: macOS Sonoma 14.5
App Version: 0.2.0-alpha (2754)

**Additional context**

**Comment by asxrow66** [comment]
Mythic doesn't say if it's downloaded or not, unless you follow the progress inside of the downloads menu in the sidebar, make sure you have enough storage as there is not an error for insufficient space.

**Comment by asxrow66** [comment]
@sauciss0nsec update? Check the storage space left on your device.

**Comment by asxrow66** [comment]
for one, gta is incompatible. try updating mythic to the newest version (0.2.1) and try it again

**Comment by sauciss0nsec** [comment]
I tried with the last update of mythic, but the issue is still there.

**Comment by sauciss0nsec** [comment]
Hi, little update : the game was downloaded thanks to the 0.3.0 version of Mythic. Despite of this, GTA 5 do not want to run because the game launcher is missing.

**Comment by asxrow66** [comment]
Someone had a way to work it, here are the steps.
1. Download Rockstar Games Launcher and Import it, follow Steam method [here](https://youtu.be/XdX315djRps)

2. Launch RockstarLauncher.exe then RockstarPatcher.exe

3. Open GTA from Mythic

@Vizual on Discord.. ![image](https://github.com/MythicApp/Mythic/assets/71299637/6e4bd206-8f4a-4b99-bfb2-4ea8610ea70a)

**Comment by sauciss0nsec** [comment]
I tried but the rockstar game installer is blocked at the install of visual C++

**Comment by jeremybosma** [comment]
fixed in 0.3.0
