### ISSUE TITLE
Steam not running

### ISSUE THREAD

**Issue by ChiliBeane** [MythicApp/Mythic#96]
**Describe the bug**
When attempting to run steam and some other apps, nothing happens.

**To Reproduce**
Dont know how. 
all im doing is just opening an app.

**Expected behavior**
Steam to open

**Screenshots**
N/A

**Mac (please complete the following information):**
Model: MacBook Air
Operating System: macOS Sonoma 14.5
App Version: 0.1.1

**Additional context**

**Comment by asxrow66** [comment]
Mythic Engine isssue, needs to be fixed ASAP. This might work, might not though, try uninstalling Mythic using [AppCleaner](https://freemacsoft.net/appcleaner/), drag the `Mythic.app` file into [AppCleaner](https://freemacsoft.net/appcleaner/) and press `Remove` in the bottom right of the window. Reinstall Mythic, currently, I recommend the 0.1.1-alpha version of Mythic. When finished setting it up and onboarding is finished, Mythic will prompt you to install an `Engine Update`, press `Cancel` on the menus that pop up and that should hopefully fix your issue, but if not, I would wait until the next [Engine](https://github.com/MythicApp/Engine) update as this is what this seems. Please fix ASAP @blackxfiied .

**Comment by jeremybosma** [comment]
This issue was because our Mythic engine was broken, open Mythic and click update when it tells you to, after that you should be able to run your games/software again. For if anything happens again join our discord https://discord.gg/qbc32gtZDt if you want a live blog on our fix.
