### ISSUE TITLE
[BUG] Adding or deleting custom launch arguments does not save

### ISSUE THREAD

**Issue by jeremybosma** [MythicApp/Mythic#99]
**Describe the bug**

**To Reproduce**
1. Go to game settings
2. Create a launch argument and click enter
3. Close and open game settings
4. See that it's gone
Same goes for removing one you had already made on 0.2.0 where it did work.

**Expected behavior**
It should save.

**Comment by marcusziade** [comment]
@jeremybosma plz remove me as assignee on all 5 tickets including this one. i can't do that myself :)

**Comment by jeremybosma** [comment]
> @jeremybosma plz remove me as assignee on all 5 tickets including this one. i can't do that myself :)

No problem, really hate to see you leave. Was really appreciating your work and especially the pace.
